### ISSUE TITLE
option to specify input files for SuperMatrix

### ISSUE THREAD

**Issue by alexweisberg** [coleoguy/evobir#18]
The SuperMatrix function is fantastic for making concatenated alignments for a set of genes and has been very useful for my research. I was wondering if it would be possible to add an option to specify the input files, or a pattern for input files? If I have a bunch of alignments in a folder but also an R script, SuperMatrix tries to read in the script as well. If there was something like something like:
SuperMatrix(input="*.aln") 
or something similar that would be very helpful. For now I have to make a separate folder that only contains the alignments, and then set the R working directory to that folder. It works but it would be nice to have an extra option.

**Comment by coleoguy** [comment]
Hi Alex,

This was a great idea! I have added it to the function. By default, the argument is left empty and will lead to the same behavior as the previous version of the function. However, if as in your example input="*.aln" then only those files ending .aln will be read in. Let me know if it gives you any problems.

cheers

Heath

**Comment by alexweisberg** [comment]
Hi Heath,

Thank you for implementing this, I appreciate it!

Best, Alex
